# Generated by Django 3.2.25 on 2024-05-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
